name: Run Tests

on: 
  pull_request:
    paths:
      - 'backend/**'
  push:
    paths:
      - 'backend/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Set environment variables
        env:
          RPC_NODE: ${{ secrets.RPC_NODE }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          SECRET: ${{ secrets.SECRET }}
        run: echo "Environment variables loaded"

      - name: Run tests
        run: npx hardhat test
        working-directory: ./backend
        env:
          RPC_NODE: ${{ secrets.RPC_NODE }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          SECRET: ${{ secrets.SECRET }}
